### ISSUE TITLE
Segfault from IsPointed( fan)

### ISSUE THREAD

**Issue by HereAround** [homalg-project/NConvex#4]
On Plesken, the following code leads to a Segfault:

LoadPackage( "NConvex" );
rays := [[1,0],[0,1],[-1,-1]];
max_coes := [[1,2],[1,3],[2,3]];
f := Fan( rays, max_cones );
IsPointed( f );

I believe that this can be resolved by updating CddInterface to the latest version on Plesken.

**Comment by kamalsaleh** [comment]
Thank you for reporting this Martin. You can either create your own local pkg's directory and change the gap starter in `/home/bies/bin/gap` to take the new location into consideration. In this new location, you can also install your own packages.

Another solution would be to automatically compile the file `update.sh` at `/opt/gap/gap_pkg` periodically, e.g. every few days. @zickgraf  can you please take care of this? or at least manually update the package?

**Comment by HereAround** [comment]
Thanks Kamal. Indeed, I was able to create my own CddInterface and compile it. Thereby the error indeed disappears.

I leave this issue open to discuss automatic compilations as you proposed.

**Comment by kamalsaleh** [comment]
The automation works now and the packages will be updated every night, thanks to @zickgraf .
